-- schema

-- !Ups
CREATE TABLE CREATE_REQUESTS (
    "ID"            BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    "NAME"          VARCHAR(255) NOT NULL,
    "DESCRIPTION"   VARCHAR(10000),
    GOAL            BIGINT NOT NULL,
    DEADLINE_HEIGHT BIGINT NOT NULL,
    CHARITY_PERCENT INT NOT NULL,
    CHARITY_ADDR    VARCHAR(10000) NOT NULL,
    TICKET_PRICE    BIGINT NOT NULL,
    "STATE"         INT,
    WALLET_ADDR     VARCHAR(10000),
    PAYMENT_ADDR    VARCHAR(10000),
    CREATE_TX_ID    VARCHAR(100),
    MERGE_TX_ID     VARCHAR(100),
    CHAINED_WITH    BIGINT,
    IS_CHAINED      BOOLEAN,
    TIME_OUT        BIGINT,
    "TTL"           BIGINT
);

CREATE TABLE DONATE_REQUESTS (
    "ID"            BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TICKET_COUNT    BIGINT NOT NULL,
    TICKET_PRICE    BIGINT NOT NULL,
    RAFFLE_DEADLINE BIGINT NOT NULL,
    "STATE"         INT,
    PAYMENT_ADD     VARCHAR(10000),
    RAFFLE_ADD      VARCHAR(10000),
    RAFFLE_TOKEN    VARCHAR(10000),
    DONATE_TX_ID    VARCHAR(1000000),
    PARTICIPANT_ADD VARCHAR(10000),
    TIME_OUT        BIGINT,
    "TTL"           BIGINT
);

CREATE TABLE ACTIVE_RAFFLES (
    "ID"            BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    MIN_TO_RAISE    BIGINT NOT NULL,
    DEADLINE_HEIGHT BIGINT NOT NULL,
    WINNER_PERCENT  INT NOT NULL,
    CHARITY_ADD     VARCHAR(10000) NOT NULL,
    TICKET_PRICE    BIGINT NOT NULL,
    "STATE"         INT,
    RAFFLE_ADD      VARCHAR(10000),
    RAFFLE_TOKEN    VARCHAR(10000),
    WINNER_BOX_ID   VARCHAR(10000),
    TIME_OUT        BIGINT,
    IS_UPDATING     BOOLEAN
);

-- !Downs
