-- schema

-- !Ups
CREATE TABLE CREATE_REQUESTS (
    "ID"            BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    "NAME"          VARCHAR(255) NOT NULL,
    "DESCRIPTION"   VARCHAR(10000),
    MIN_TO_RAISE    BIGINT NOT NULL,
    DEADLINE_HEIGHT BIGINT NOT NULL,
    WINNER_PERCENT  INT NOT NULL,
    CHARITY_ADD     VARCHAR(10000) NOT NULL,
    TICKET_PRICE    BIGINT NOT NULL,
    "STATE"         INT,
    PAYMENT_ADD     VARCHAR(10000),
    PROXY_ADD       VARCHAR(10000),
    RAFFLE_ADD      VARCHAR(10000),
    RAFFLE_TOKEN    VARCHAR(10000),
    SERVICE_BOX_ID  VARCHAR(10000),
    S_PROXY_TX      VARCHAR(1000000),
    S_CREATE_TX     VARCHAR(1000000),
    CHAINED_WITH    BIGINT,
    IS_CHAINED      BOOLEAN,
    TIME_OUT        BIGINT,
    "TTL"           BIGINT
);

CREATE TABLE DONATE_REQUESTS (
    "ID"            BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TICKET_COUNT    BIGINT NOT NULL,
    TICKET_PRICE    BIGINT NOT NULL,
    "STATE"         INT,
    PAYMENT_ADD     VARCHAR(10000),
    RAFFLE_ADD      VARCHAR(10000),
    RAFFLE_TOKEN    VARCHAR(10000),
    S_DONATE_TX     VARCHAR(1000000),
    PARTICIPANT_ADD VARCHAR(10000),
    TICKET_ADD      VARCHAR(10000),
    TIME_OUT        BIGINT,
    "TTL"           BIGINT
);

CREATE TABLE REFUND_REQUESTS (
    "ID"            BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TICKET_COUNT    BIGINT NOT NULL,
    TICKET_PRICE    BIGINT NOT NULL,
    "STATE"         INT,
    RAFFLE_ADD      VARCHAR(10000),
    RAFFLE_TOKEN    VARCHAR(10000),
    S_REFUND_TX     VARCHAR(1000000),
    TICKET_ADD      VARCHAR(10000),
    TIME_OUT        BIGINT
);

CREATE TABLE ACTIVE_RAFFLES (
    "ID"            BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    MIN_TO_RAISE    BIGINT NOT NULL,
    DEADLINE_HEIGHT BIGINT NOT NULL,
    WINNER_PERCENT  INT NOT NULL,
    CHARITY_ADD     VARCHAR(10000) NOT NULL,
    TICKET_PRICE    BIGINT NOT NULL,
    "STATE"         INT,
    RAFFLE_ADD      VARCHAR(10000),
    RAFFLE_TOKEN    VARCHAR(10000),
    WINNER_BOX_ID   VARCHAR(10000),
    TIME_OUT        BIGINT,
    IS_UPDATING     BOOLEAN
);

-- !Downs
